package com.jbass.orbital.domain.model

import kotlinx.serialization.Serializable


/**
 * All messages sent FROM Client TO Server are wrapped in this Sealed Class.
 * This allows the Server to listen for specific types of messages.
 */
@Serializable
sealed class ClientMessage {

    @Serializable
    data class Subscribe(
        val requestId: String, // UUID generated by the App
        val subscribeZones: Set<String> = emptySet(),
        val unsubscribeZones: Set<String> = emptySet()
    ) : ClientMessage()

    @Serializable
    data class Command(
        val requestId: String, // UUID generated by the App
        val deviceId: String,
        val newState: DeviceState,
        val zoneId: String? = null
    ) : ClientMessage()
}